version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/app_of_control_tasks
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=control

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=app_of_control_tasks
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=control
    volumes:
      - postgres_data:/var/lib/postgresql/data
